// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Switch_and_Shift.Models;

namespace Switch_and_Shift.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240914134307_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Switch_and_Shift.Models.ADMIN", b =>
                {
                    b.Property<int>("Admin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Admin_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Admin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Admin_Password")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Admin_ID");

                    b.ToTable("ADMIN");
                });

            modelBuilder.Entity("Switch_and_Shift.Models.CATEGORIES", b =>
                {
                    b.Property<int>("categories_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categories_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categories_id");

                    b.ToTable("CATEGORIES");
                });

            modelBuilder.Entity("Switch_and_Shift.Models.PRODUCTS", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("image_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("post_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("product_price")
                        .HasColumnType("int");

                    b.Property<string>("product_usage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_warranty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Product_ID");

                    b.ToTable("PRODUCTS");
                });

            modelBuilder.Entity("Switch_and_Shift.Models.REPORT", b =>
                {
                    b.Property<int>("report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("buyer_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("product_price")
                        .HasColumnType("int");

                    b.Property<string>("seller_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seller_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("report_Id");

                    b.ToTable("REPORT");
                });

            modelBuilder.Entity("Switch_and_Shift.Models.REPORTS_ADMIN", b =>
                {
                    b.Property<int>("report_admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("report_show")
                        .HasColumnType("int");

                    b.Property<string>("reportee_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reportee_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reporter_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reporter_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("report_admin_id");

                    b.ToTable("REPORTS_ADMIN");
                });

            modelBuilder.Entity("Switch_and_Shift.Models.USERREVIEW", b =>
                {
                    b.Property<int>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("post_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("review_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reviewee_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reviewee_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reviewer_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reviewer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("review_id");

                    b.ToTable("USERREVIEW");
                });

            modelBuilder.Entity("Switch_and_Shift.Models.USERS", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("report_show")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
